### ISSUE TITLE
Dúvida no exercicio3

### ISSUE THREAD

**Issue by pulgamecanica** [ULHT-PW-2020-21/pw-python-03#1]
No exercicio 3 é pedido:

> Crie um programa que utilize a função, utilizando a função pede_nome do modulo do exercicio 1.

Penso que há um engano, pois no exercicio nao pretendemos obter um ficheiro e sim uma pasta!
Penso que secalhar o que querem é utilizar a função _**pede_pasta**_ do exercicio 2. Pois, no exercico 3 precisamos de uma pasta e nao um ficheiro.

**Comment by luciostuder** [comment]
Obrigado pela correção. Alterei a frase para:

Crie um programa que utilize a função, utilizando uma função semelhante a pede_nome do modulo do exercicio 1, para pedir o nome de uma pasta para analisar

**Comment by pulgamecanica** [comment]
Boa, então tambem vou adaptar o meu código para cumprir com ese requisito! 
Obrigado e bom fim de semana.
